// ============================================================
// EEOS DEMONSTRATION DATA
// Used exclusively for the interactive product demo.
// No real company data. No AI reasoning. No backend logic.
// ============================================================

export const DEMO_COMPANY = {
  name: "Meridian Home Services",
  industry: "multi-location service",
  ceo: "Alexandra Chen",
  employees: 84,
  revenue: "$8.4M",
  locations: 4,
  departments: 6,
};

// Executive Dashboard KPIs
export const DASHBOARD_KPIS = [
  {
    id: "revenue",
    label: "Revenue YTD",
    value: "$6.2M",
    change: "+12.4%",
    trend: "up",
    sparkline: [42, 45, 43, 48, 52, 56, 58, 62],
    status: "green",
  },
  {
    id: "ops-efficiency",
    label: "Ops Efficiency",
    value: "87.3%",
    change: "+3.1%",
    trend: "up",
    sparkline: [78, 80, 79, 82, 84, 85, 86, 87],
    status: "green",
  },
  {
    id: "talent-risk",
    label: "Talent Risk Index",
    value: "Medium",
    change: "2 new flags",
    trend: "neutral",
    sparkline: [30, 28, 32, 35, 33, 36, 38, 35],
    status: "amber",
  },
  {
    id: "market-position",
    label: "Lead Flow",
    value: "Strong",
    change: "Stable",
    trend: "neutral",
    sparkline: [2, 2, 3, 2, 2, 2, 2, 2],
    status: "green",
  },
  {
    id: "supply-chain",
    label: "Operations Health",
    value: "74%",
    change: "-5.2%",
    trend: "down",
    sparkline: [85, 83, 80, 79, 78, 76, 75, 74],
    status: "amber",
  },
  {
    id: "innovation-index",
    label: "AI Readiness",
    value: "91",
    change: "+7 pts",
    trend: "up",
    sparkline: [72, 75, 78, 80, 83, 86, 89, 91],
    status: "green",
  },
];

// Executive Priorities
export const PRIORITIES = [
  {
    id: "p1",
    priority: 1,
    title: "Follow-Up Gap — New Lead Response",
    category: "Operations",
    urgency: "Critical",
    impact: "High",
    timeframe: "48 hours",
    description:
      "New lead response has slowed across two locations. EEOS recommends immediate follow-up before opportunities cool.",
    actions: ["Contact unassigned leads", "Review missed-call follow-up", "Assign owner for today's intake"],
    confidence: 94,
    sources: 12,
  },
  {
    id: "p2",
    priority: 2,
    title: "Owner Brief — Weekly Growth Review",
    category: "Strategy",
    urgency: "High",
    impact: "High",
    timeframe: "5 days",
    description:
      "Weekly owner review requires a clear readout on lead flow, operations, staffing, and follow-up performance.",
    actions: ["Review business health", "Confirm weekly priorities", "Assign follow-up actions"],
    confidence: 88,
    sources: 8,
  },
  {
    id: "p3",
    priority: 3,
    title: "Staffing Coverage — Weekend Risk",
    category: "People",
    urgency: "High",
    impact: "Medium",
    timeframe: "2 weeks",
    description:
      "Weekend staffing signals show potential coverage gaps in one location. Early action can prevent service disruption.",
    actions: ["Review caregiver availability", "Confirm weekend assignments", "Escalate open shifts"],
    confidence: 79,
    sources: 6,
  },
  {
    id: "p4",
    priority: 4,
    title: "Customer Care — Waiting Assessments",
    category: "Legal",
    urgency: "Medium",
    impact: "Medium",
    timeframe: "3 weeks",
    description:
      "Two assessments are waiting to be scheduled. EEOS recommends contacting those families today.",
    actions: ["Schedule assessments", "Update task owners", "Confirm appointment calendar"],
    confidence: 85,
    sources: 9,
  },
  {
    id: "p5",
    priority: 5,
    title: "Automation Opportunity — Intake Workflow",
    category: "Technology",
    urgency: "Medium",
    impact: "High",
    timeframe: "6 weeks",
    description:
      "Intake activity suggests a workflow automation opportunity that could reduce manual follow-up and owner oversight.",
    actions: ["Review intake steps", "Identify manual handoffs", "Approve workflow improvement"],
    confidence: 72,
    sources: 5,
  },
];

// Business DNA
export const BUSINESS_DNA = {
  coreStrengths: [
    { label: "Lead Response", score: 94, trend: "stable" },
    { label: "Customer Care", score: 91, trend: "up" },
    { label: "Referral Relationships", score: 88, trend: "up" },
    { label: "Operations Discipline", score: 85, trend: "stable" },
    { label: "Staffing Coverage", score: 74, trend: "down" },
    { label: "Automation Readiness", score: 68, trend: "up" },
  ],
  riskFactors: [
    { label: "Geopolitical Exposure", level: "Medium", score: 45 },
    { label: "Talent Concentration", level: "High", score: 72 },
    { label: "Single-Source Dependencies", level: "Medium", score: 38 },
    { label: "Regulatory Complexity", level: "Low", score: 22 },
  ],
  strategicThemes: [
    { theme: "Local Market Expansion", alignment: 92, momentum: "accelerating" },
    { theme: "Referral Growth", alignment: 87, momentum: "growing" },
    { theme: "AI Integration", alignment: 78, momentum: "growing" },
    { theme: "Sustainability Compliance", alignment: 65, momentum: "stable" },
    { theme: "Workforce Transformation", alignment: 71, momentum: "stable" },
  ],
  departments: [
    { name: "Sales & Intake", health: 88, headcount: 8, budget: "$1.2M" },
    { name: "Operations", health: 92, headcount: 16, budget: "$2.1M" },
    { name: "Staffing", health: 74, headcount: 38, budget: "$0.8M" },
    { name: "Customer Care", health: 91, headcount: 10, budget: "$1.5M" },
    { name: "Finance", health: 85, headcount: 4, budget: "$0.2M" },
    { name: "Leadership", health: 79, headcount: 3, budget: "$0.15M" },
    { name: "Compliance", health: 83, headcount: 3, budget: "$0.1M" },
    { name: "Technology", health: 77, headcount: 2, budget: "$0.6M" },
  ],
};

// Recommendation Cards
export const RECOMMENDATIONS = [
  {
    id: "r1",
    type: "action",
    urgency: "critical",
    title: "Recover Missed Opportunities",
    summary: "Contact warm leads before today's response window closes.",
    detail:
      "EEOS has identified a same-day decision window. Acting now protects an estimated $34K in open opportunity value. Waiting until tomorrow increases the chance of losing those inquiries.",
    confidence: 94,
    timeToAct: "48 hours",
    potentialValue: "$34K protected",
    category: "Operations",
    icon: "alert-triangle",
  },
  {
    id: "r2",
    type: "opportunity",
    urgency: "high",
    title: "Referral Growth — Partner Outreach",
    summary: "Recent referral patterns suggest a focused partner outreach opportunity.",
    detail:
      "EEOS detected stronger conversion from two referral sources. A focused outreach campaign could increase qualified opportunities over the next 10 days.",
    confidence: 81,
    timeToAct: "10 days",
    potentialValue: "$28K opportunity",
    category: "Strategy",
    icon: "trending-up",
  },
  {
    id: "r3",
    type: "risk",
    urgency: "high",
    title: "Staffing Coverage Signal",
    summary: "Weekend coverage is showing early strain in one location.",
    detail:
      "Staffing and availability signals suggest elevated coverage risk in one service area. Early action can protect service quality and reduce owner escalation.",
    confidence: 79,
    timeToAct: "2 weeks",
    potentialValue: "$58K risk mitigation",
    category: "People",
    icon: "users",
  },
  {
    id: "r4",
    type: "insight",
    urgency: "medium",
    title: "Local Market Opportunity",
    summary: "Competitor response delays create a window to win more inquiries.",
    detail:
      "Local competitors are responding slowly to after-hours inquiries. Meridian can capture more opportunities by routing AI calls and chats into faster follow-up workflows.",
    confidence: 73,
    timeToAct: "6 weeks",
    potentialValue: "$110K opportunity",
    category: "Market",
    icon: "zap",
  },
];

// Timeline Events
export const TIMELINE_EVENTS = [
  {
    id: "t1",
    date: "2025-07-09",
    time: "08:42",
    title: "Lead Response Alert Triggered",
    category: "Operations",
    severity: "critical",
    description: "EEOS detected slower follow-up on new inquiries from connected business activity.",
    automated: true,
  },
  {
    id: "t2",
    date: "2025-07-08",
    time: "14:15",
    title: "Owner Brief Synthesis Complete",
    category: "Strategy",
    severity: "info",
    description: "EEOS synthesized connected activity into an owner-ready executive briefing draft.",
    automated: true,
  },
  {
    id: "t3",
    date: "2025-07-07",
    time: "09:30",
    title: "Referral Opportunity Identified",
    category: "Strategy",
    severity: "high",
    description: "New referral growth opportunity flagged from recent partner activity.",
    automated: true,
  },
  {
    id: "t4",
    date: "2025-07-05",
    time: "11:00",
    title: "Staffing Risk Report Generated",
    category: "People",
    severity: "high",
    description: "Weekly staffing intelligence report flagged one service area as needing coverage review.",
    automated: true,
  },
  {
    id: "t5",
    date: "2025-07-03",
    time: "16:45",
    title: "Compliance Review Completed",
    category: "Legal",
    severity: "medium",
    description: "Compliance review completed. Three follow-up items identified for owner review.",
    automated: false,
  },
  {
    id: "t6",
    date: "2025-07-01",
    time: "08:00",
    title: "Monthly Intelligence Briefing",
    category: "Executive",
    severity: "info",
    description: "EEOS generated a monthly briefing covering business health, operations, staffing, and growth signals.",
    automated: true,
  },
  {
    id: "t7",
    date: "2025-06-28",
    time: "10:20",
    title: "Local Market Analysis Update",
    category: "Market",
    severity: "medium",
    description: "Competitor response delays detected. Local opportunity window calculated.",
    automated: true,
  },
  {
    id: "t8",
    date: "2025-06-25",
    time: "14:00",
    title: "Workflow Automation Milestone",
    category: "Technology",
    severity: "info",
    description: "Initial automation review completed. Owner approval required for the next workflow improvement.",
    automated: false,
  },
];

// Knowledge Graph Nodes
export const KNOWLEDGE_GRAPH = {
  nodes: [
    { id: "ceo", label: "CEO", type: "executive", x: 400, y: 300, size: 28 },
    { id: "cfo", label: "CFO", type: "executive", x: 250, y: 180, size: 22 },
    { id: "ops-lead", label: "Ops Lead", type: "executive", x: 550, y: 180, size: 22 },
    { id: "care-lead", label: "Care Lead", type: "executive", x: 250, y: 420, size: 22 },
    { id: "growth-lead", label: "Growth Lead", type: "executive", x: 550, y: 420, size: 22 },
    { id: "finance", label: "Finance", type: "department", x: 120, y: 120, size: 16 },
    { id: "automation", label: "Automation", type: "department", x: 680, y: 120, size: 18 },
    { id: "intake", label: "Intake", type: "department", x: 100, y: 350, size: 16 },
    { id: "staffing", label: "Staffing", type: "department", x: 680, y: 350, size: 18 },
    { id: "operations", label: "Operations", type: "department", x: 400, y: 480, size: 18 },
    { id: "compliance", label: "Compliance", type: "department", x: 160, y: 480, size: 14 },
    { id: "referrals", label: "Referrals", type: "external", x: 400, y: 80, size: 14 },
    { id: "missed-calls", label: "Missed Calls", type: "risk", x: 80, y: 240, size: 14 },
    { id: "competitor", label: "Competitor", type: "opportunity", x: 720, y: 240, size: 12 },
    { id: "reviews", label: "Reviews", type: "external", x: 160, y: 560, size: 12 },
    { id: "ai", label: "AI Assistant", type: "department", x: 640, y: 480, size: 16 },
  ],
  edges: [
    { source: "ceo", target: "cfo", weight: 3 },
    { source: "ceo", target: "ops-lead", weight: 3 },
    { source: "ceo", target: "care-lead", weight: 3 },
    { source: "ceo", target: "growth-lead", weight: 3 },
    { source: "cfo", target: "finance", weight: 2 },
    { source: "ops-lead", target: "automation", weight: 2 },
    { source: "ops-lead", target: "staffing", weight: 2 },
    { source: "care-lead", target: "intake", weight: 2 },
    { source: "care-lead", target: "operations", weight: 2 },
    { source: "growth-lead", target: "staffing", weight: 1 },
    { source: "operations", target: "referrals", weight: 2 },
    { source: "intake", target: "missed-calls", weight: 2, risk: true },
    { source: "automation", target: "ai", weight: 2 },
    { source: "ai", target: "competitor", weight: 1, opportunity: true },
    { source: "compliance", target: "reviews", weight: 1 },
    { source: "ceo", target: "referrals", weight: 1 },
    { source: "staffing", target: "operations", weight: 2 },
    { source: "finance", target: "care-lead", weight: 1 },
  ],
};

// Integration logos for Integration Readiness page
export const INTEGRATIONS = [
  { name: "GoHighLevel", category: "Business System", logo: "GHL", color: "#C9A227" },
  { name: "SAP", category: "ERP", logo: "SAP", color: "#0FAAFF" },
  { name: "Oracle ERP", category: "ERP", logo: "ORC", color: "#F80000" },
  { name: "Microsoft 365", category: "Productivity", logo: "M365", color: "#0078D4" },
  { name: "Workday", category: "HR", logo: "WD", color: "#F36F21" },
  { name: "ServiceNow", category: "ERP", logo: "SN", color: "#81B5A1" },
  { name: "Slack", category: "Productivity", logo: "SLK", color: "#4A154B" },
  { name: "Tableau", category: "Analytics", logo: "TAB", color: "#E97627" },
  { name: "Power BI", category: "Analytics", logo: "PBI", color: "#F2C811" },
  { name: "Jira", category: "Productivity", logo: "JRA", color: "#0052CC" },
  { name: "HubSpot", category: "Business System", logo: "HS", color: "#FF7A59" },
  { name: "Snowflake", category: "Analytics", logo: "SNW", color: "#29B5E8" },
  { name: "NetSuite", category: "ERP", logo: "NS", color: "#2F9E44" },
  { name: "SAP SuccessFactors", category: "HR", logo: "SF2", color: "#0070F3" },
  { name: "ADP", category: "HR", logo: "ADP", color: "#D0021B" },
  { name: "Workday Finance", category: "Finance", logo: "WF", color: "#F36F21" },
  { name: "Oracle Finance", category: "Finance", logo: "OF", color: "#F80000" },
  { name: "Coupa", category: "Finance", logo: "CPA", color: "#E31837" },
  { name: "Looker", category: "Analytics", logo: "LKR", color: "#4285F4" },
  { name: "Google Workspace", category: "Productivity", logo: "GWS", color: "#4285F4" },
  { name: "Microsoft Dynamics", category: "ERP", logo: "MSF", color: "#0078D4" },
  { name: "Qlik", category: "Analytics", logo: "QLK", color: "#009845" },
  { name: "BambooHR", category: "HR", logo: "BHR", color: "#73C41D" },
  { name: "Concur", category: "Finance", logo: "CNR", color: "#0070F3" },
];

// Industries served
export const INDUSTRIES = [
  {
    id: "home-services",
    name: "Home Services",
    icon: "🏠",
    description: "Executive intelligence for local and multi-location operators managing leads, teams, jobs, and customer response.",
    metrics: { avgROI: "340%", timeToValue: "6 weeks", clients: "12+" },
    useCases: ["Lead response visibility", "AI call handling", "Operations health", "Customer care follow-up"],
  },
  {
    id: "financial",
    name: "Professional Services",
    icon: "🏦",
    description: "Decision support for firms that need better visibility into pipeline, client delivery, tasks, and referrals.",
    metrics: { avgROI: "280%", timeToValue: "4 weeks", clients: "18+" },
    useCases: ["Pipeline health", "Task prioritization", "Referral tracking", "Performance benchmarking"],
  },
  {
    id: "healthcare",
    name: "Healthcare Services",
    icon: "⚕️",
    description: "Operational intelligence for care providers, staffing teams, and small healthcare operators.",
    metrics: { avgROI: "310%", timeToValue: "8 weeks", clients: "9+" },
    useCases: ["Assessment follow-up", "Staffing coverage", "Referral response", "Workflow automation"],
  },
  {
    id: "manufacturing",
    name: "Local Operations",
    icon: "⚙️",
    description: "Business health monitoring for operators who need tighter scheduling, staffing, and execution visibility.",
    metrics: { avgROI: "295%", timeToValue: "5 weeks", clients: "15+" },
    useCases: ["Scheduling health", "Capacity planning", "Quality signals", "Team utilization"],
  },
  {
    id: "energy",
    name: "Field Services",
    icon: "⚡",
    description: "AI operating visibility for businesses with mobile teams, urgent requests, and high response expectations.",
    metrics: { avgROI: "260%", timeToValue: "7 weeks", clients: "8+" },
    useCases: ["Missed-call recovery", "Dispatch visibility", "Customer response", "Operational alerts"],
  },
  {
    id: "technology",
    name: "Growth Companies",
    icon: "💻",
    description: "Executive intelligence for small businesses preparing to scale with stronger systems and clearer decisions.",
    metrics: { avgROI: "320%", timeToValue: "3 weeks", clients: "22+" },
    useCases: ["Business health score", "Workflow automation", "Growth signals", "Executive dashboards"],
  },
];

// Pricing tiers
export const PRICING_TIERS = [
  {
    id: "command",
    name: "Command",
    tagline: "For growing small businesses",
    price: "Contact Sales",
    priceNote: "Starting at $4,800/month",
    highlight: false,
    features: [
      "Up to 5 executive users",
      "Executive Dashboard",
      "Priority Intelligence Feed",
      "GoHighLevel integration",
      "Standard onboarding",
      "Email support",
      "Quarterly business reviews",
    ],
    cta: "Request Access",
  },
  {
    id: "sovereign",
    name: "Sovereign",
    tagline: "For multi-location operators",
    price: "Contact Sales",
    priceNote: "Starting at $9,800/month",
    highlight: true,
    features: [
      "Up to 25 executive users",
      "Full Executive Intelligence Suite",
      "Business DNA & Knowledge Graph",
      "Advanced GoHighLevel intelligence",
      "Dedicated onboarding specialist",
      "24/7 priority support",
      "Monthly executive briefings",
      "Custom recommendation models",
      "API access",
    ],
    cta: "Request Access",
  },
  {
    id: "apex",
    name: "Apex",
    tagline: "For complex organizations",
    price: "Contact Sales",
    priceNote: "Custom enterprise pricing",
    highlight: false,
    features: [
      "Unlimited executive users",
      "Full platform + custom modules",
      "White-glove implementation",
      "Dedicated success team",
      "Custom AI model training",
      "On-premise deployment option",
      "SLA guarantees",
      "Board-level reporting",
      "Multi-entity support",
    ],
    cta: "Schedule Briefing",
  },
];
