// ============================================================
// EEOS DEMONSTRATION DATA
// Used exclusively for the interactive product demo.
// No real company data. No AI reasoning. No backend logic.
// ============================================================

export const DEMO_COMPANY = {
  name: "Meridian Global Corp",
  industry: "Aerospace & Defense",
  ceo: "Alexandra Chen",
  employees: 42800,
  revenue: "$8.4B",
  locations: 23,
  departments: 14,
};

// Executive Dashboard KPIs
export const DASHBOARD_KPIS = [
  {
    id: "revenue",
    label: "Revenue YTD",
    value: "$6.2B",
    change: "+12.4%",
    trend: "up",
    sparkline: [42, 45, 43, 48, 52, 56, 58, 62],
    status: "green",
  },
  {
    id: "ops-efficiency",
    label: "Ops Efficiency",
    value: "87.3%",
    change: "+3.1%",
    trend: "up",
    sparkline: [78, 80, 79, 82, 84, 85, 86, 87],
    status: "green",
  },
  {
    id: "talent-risk",
    label: "Talent Risk Index",
    value: "Medium",
    change: "2 new flags",
    trend: "neutral",
    sparkline: [30, 28, 32, 35, 33, 36, 38, 35],
    status: "amber",
  },
  {
    id: "market-position",
    label: "Market Position",
    value: "#2",
    change: "Stable",
    trend: "neutral",
    sparkline: [2, 2, 3, 2, 2, 2, 2, 2],
    status: "green",
  },
  {
    id: "supply-chain",
    label: "Supply Chain Health",
    value: "74%",
    change: "-5.2%",
    trend: "down",
    sparkline: [85, 83, 80, 79, 78, 76, 75, 74],
    status: "amber",
  },
  {
    id: "innovation-index",
    label: "Innovation Index",
    value: "91",
    change: "+7 pts",
    trend: "up",
    sparkline: [72, 75, 78, 80, 83, 86, 89, 91],
    status: "green",
  },
];

// Executive Priorities
export const PRIORITIES = [
  {
    id: "p1",
    priority: 1,
    title: "Supply Chain Disruption — APAC Tier-2",
    category: "Operations",
    urgency: "Critical",
    impact: "High",
    timeframe: "48 hours",
    description:
      "Three Tier-2 suppliers in Malaysia have flagged capacity constraints affecting Q4 delivery schedules. Estimated $340M revenue impact if unaddressed.",
    actions: ["Activate backup supplier protocol", "Schedule emergency procurement review", "Brief CFO on hedge options"],
    confidence: 94,
    sources: 12,
  },
  {
    id: "p2",
    priority: 2,
    title: "Board Presentation — Strategic Roadmap 2026",
    category: "Strategy",
    urgency: "High",
    impact: "High",
    timeframe: "5 days",
    description:
      "Board meeting requires updated 3-year strategic roadmap incorporating the Nexus acquisition scenario and defense contract expansion.",
    actions: ["Review M&A analysis", "Finalize scenario modeling", "Align with CFO and CLO"],
    confidence: 88,
    sources: 8,
  },
  {
    id: "p3",
    priority: 3,
    title: "Talent Retention — Engineering Division",
    category: "People",
    urgency: "High",
    impact: "Medium",
    timeframe: "2 weeks",
    description:
      "Attrition signals detected in aerospace engineering team. 14 senior engineers showing disengagement patterns. Competitor poaching activity elevated.",
    actions: ["Initiate retention package review", "Schedule 1:1 with division heads", "Benchmark compensation"],
    confidence: 79,
    sources: 6,
  },
  {
    id: "p4",
    priority: 4,
    title: "Regulatory Filing — EU Compliance Update",
    category: "Legal",
    urgency: "Medium",
    impact: "Medium",
    timeframe: "3 weeks",
    description:
      "New EU defense export regulations require updated compliance documentation for 7 product lines. Legal team has flagged 3 potential gaps.",
    actions: ["Legal review completion", "Update product documentation", "File regulatory submissions"],
    confidence: 85,
    sources: 9,
  },
  {
    id: "p5",
    priority: 5,
    title: "Digital Transformation Initiative — Phase 2",
    category: "Technology",
    urgency: "Medium",
    impact: "High",
    timeframe: "6 weeks",
    description:
      "Phase 2 of the enterprise digital transformation requires executive sign-off on cloud migration strategy and budget reallocation of $45M.",
    actions: ["CTO briefing", "Budget committee review", "Vendor selection finalization"],
    confidence: 72,
    sources: 5,
  },
];

// Business DNA
export const BUSINESS_DNA = {
  coreStrengths: [
    { label: "Defense Contracts", score: 94, trend: "stable" },
    { label: "R&D Capability", score: 91, trend: "up" },
    { label: "Government Relations", score: 88, trend: "up" },
    { label: "Manufacturing Scale", score: 85, trend: "stable" },
    { label: "Supply Chain Network", score: 74, trend: "down" },
    { label: "Digital Maturity", score: 68, trend: "up" },
  ],
  riskFactors: [
    { label: "Geopolitical Exposure", level: "Medium", score: 45 },
    { label: "Talent Concentration", level: "High", score: 72 },
    { label: "Single-Source Dependencies", level: "Medium", score: 38 },
    { label: "Regulatory Complexity", level: "Low", score: 22 },
  ],
  strategicThemes: [
    { theme: "Defense Modernization", alignment: 92, momentum: "accelerating" },
    { theme: "Space Systems Expansion", alignment: 87, momentum: "growing" },
    { theme: "AI Integration", alignment: 78, momentum: "growing" },
    { theme: "Sustainability Compliance", alignment: 65, momentum: "stable" },
    { theme: "Workforce Transformation", alignment: 71, momentum: "stable" },
  ],
  departments: [
    { name: "Aerospace Engineering", health: 88, headcount: 8400, budget: "$1.2B" },
    { name: "Defense Systems", health: 92, headcount: 6200, budget: "$2.1B" },
    { name: "Supply Chain", health: 74, headcount: 3100, budget: "$0.8B" },
    { name: "R&D", health: 91, headcount: 4800, budget: "$1.5B" },
    { name: "Finance", health: 85, headcount: 1200, budget: "$0.2B" },
    { name: "Human Capital", health: 79, headcount: 900, budget: "$0.15B" },
    { name: "Legal & Compliance", health: 83, headcount: 600, budget: "$0.1B" },
    { name: "Technology", health: 77, headcount: 2800, budget: "$0.6B" },
  ],
};

// Recommendation Cards
export const RECOMMENDATIONS = [
  {
    id: "r1",
    type: "action",
    urgency: "critical",
    title: "Activate Tier-2 Supplier Contingency",
    summary: "Initiate backup supplier protocol for Malaysian component shortage before Q4 window closes.",
    detail:
      "EEOS has identified a 72-hour decision window. Activating the contingency protocol now preserves $340M in Q4 revenue. Delay beyond Thursday increases risk to $520M.",
    confidence: 94,
    timeToAct: "48 hours",
    potentialValue: "$340M protected",
    category: "Operations",
    icon: "alert-triangle",
  },
  {
    id: "r2",
    type: "opportunity",
    urgency: "high",
    title: "Defense Contract Expansion — DoD RFP",
    summary: "New DoD RFP aligns with core competencies. Early bid positioning recommended.",
    detail:
      "A $2.8B DoD contract opportunity has been identified that aligns with Meridian's existing defense systems portfolio. Competitive analysis shows 3 viable competitors, with Meridian holding a 34% win probability if bid is submitted within 10 days.",
    confidence: 81,
    timeToAct: "10 days",
    potentialValue: "$2.8B opportunity",
    category: "Strategy",
    icon: "trending-up",
  },
  {
    id: "r3",
    type: "risk",
    urgency: "high",
    title: "Engineering Talent Attrition Signal",
    summary: "14 senior engineers showing disengagement patterns. Competitor poaching activity detected.",
    detail:
      "Behavioral signals across communication patterns, project engagement metrics, and external activity suggest elevated flight risk in the aerospace engineering division. Estimated replacement cost: $4.2M per senior engineer.",
    confidence: 79,
    timeToAct: "2 weeks",
    potentialValue: "$58M risk mitigation",
    category: "People",
    icon: "users",
  },
  {
    id: "r4",
    type: "insight",
    urgency: "medium",
    title: "Market Share Opportunity — Space Systems",
    summary: "Competitor weakness in satellite systems creates a 6-month window for market capture.",
    detail:
      "Orbital Dynamics Inc. has experienced two failed satellite launches and is losing government contracts. Meridian's Space Systems division is positioned to capture an estimated $1.1B in redirected contracts.",
    confidence: 73,
    timeToAct: "6 weeks",
    potentialValue: "$1.1B opportunity",
    category: "Market",
    icon: "zap",
  },
];

// Timeline Events
export const TIMELINE_EVENTS = [
  {
    id: "t1",
    date: "2025-07-09",
    time: "08:42",
    title: "Supply Chain Alert Triggered",
    category: "Operations",
    severity: "critical",
    description: "EEOS detected capacity constraint signals from 3 Malaysian suppliers via integrated ERP data.",
    automated: true,
  },
  {
    id: "t2",
    date: "2025-07-08",
    time: "14:15",
    title: "Q3 Board Deck Synthesis Complete",
    category: "Strategy",
    severity: "info",
    description: "EEOS synthesized 847 data points from 12 departments into executive-ready board presentation draft.",
    automated: true,
  },
  {
    id: "t3",
    date: "2025-07-07",
    time: "09:30",
    title: "DoD RFP Opportunity Identified",
    category: "Strategy",
    severity: "high",
    description: "New defense contract opportunity flagged from government procurement database monitoring.",
    automated: true,
  },
  {
    id: "t4",
    date: "2025-07-05",
    time: "11:00",
    title: "Talent Risk Report Generated",
    category: "People",
    severity: "high",
    description: "Weekly talent intelligence report flagged 14 engineers in aerospace division as elevated flight risk.",
    automated: true,
  },
  {
    id: "t5",
    date: "2025-07-03",
    time: "16:45",
    title: "EU Regulatory Update Filed",
    category: "Legal",
    severity: "medium",
    description: "Legal team completed compliance review. 3 documentation gaps identified for executive review.",
    automated: false,
  },
  {
    id: "t6",
    date: "2025-07-01",
    time: "08:00",
    title: "Monthly Intelligence Briefing",
    category: "Executive",
    severity: "info",
    description: "EEOS generated comprehensive monthly briefing covering all 14 departments and 23 locations.",
    automated: true,
  },
  {
    id: "t7",
    date: "2025-06-28",
    time: "10:20",
    title: "Competitor Analysis Update",
    category: "Market",
    severity: "medium",
    description: "Orbital Dynamics Inc. satellite failures detected. Market opportunity window calculated.",
    automated: true,
  },
  {
    id: "t8",
    date: "2025-06-25",
    time: "14:00",
    title: "Digital Transformation Milestone",
    category: "Technology",
    severity: "info",
    description: "Phase 1 cloud migration completed. Phase 2 budget approval required from CEO.",
    automated: false,
  },
];

// Knowledge Graph Nodes
export const KNOWLEDGE_GRAPH = {
  nodes: [
    { id: "ceo", label: "CEO", type: "executive", x: 400, y: 300, size: 28 },
    { id: "cfo", label: "CFO", type: "executive", x: 250, y: 180, size: 22 },
    { id: "cto", label: "CTO", type: "executive", x: 550, y: 180, size: 22 },
    { id: "coo", label: "COO", type: "executive", x: 250, y: 420, size: 22 },
    { id: "chro", label: "CHRO", type: "executive", x: 550, y: 420, size: 22 },
    { id: "finance", label: "Finance", type: "department", x: 120, y: 120, size: 16 },
    { id: "rd", label: "R&D", type: "department", x: 680, y: 120, size: 18 },
    { id: "supplychain", label: "Supply Chain", type: "department", x: 100, y: 350, size: 16 },
    { id: "engineering", label: "Engineering", type: "department", x: 680, y: 350, size: 18 },
    { id: "defense", label: "Defense Sys", type: "department", x: 400, y: 480, size: 18 },
    { id: "legal", label: "Legal", type: "department", x: 160, y: 480, size: 14 },
    { id: "dod", label: "DoD Contract", type: "external", x: 400, y: 80, size: 14 },
    { id: "supplier-my", label: "MY Suppliers", type: "risk", x: 80, y: 240, size: 14 },
    { id: "competitor", label: "Orbital Dyn.", type: "opportunity", x: 720, y: 240, size: 12 },
    { id: "eu-reg", label: "EU Regulation", type: "external", x: 160, y: 560, size: 12 },
    { id: "space", label: "Space Systems", type: "department", x: 640, y: 480, size: 16 },
  ],
  edges: [
    { source: "ceo", target: "cfo", weight: 3 },
    { source: "ceo", target: "cto", weight: 3 },
    { source: "ceo", target: "coo", weight: 3 },
    { source: "ceo", target: "chro", weight: 3 },
    { source: "cfo", target: "finance", weight: 2 },
    { source: "cto", target: "rd", weight: 2 },
    { source: "cto", target: "engineering", weight: 2 },
    { source: "coo", target: "supplychain", weight: 2 },
    { source: "coo", target: "defense", weight: 2 },
    { source: "chro", target: "engineering", weight: 1 },
    { source: "defense", target: "dod", weight: 2 },
    { source: "supplychain", target: "supplier-my", weight: 2, risk: true },
    { source: "rd", target: "space", weight: 2 },
    { source: "space", target: "competitor", weight: 1, opportunity: true },
    { source: "legal", target: "eu-reg", weight: 1 },
    { source: "ceo", target: "dod", weight: 1 },
    { source: "engineering", target: "defense", weight: 2 },
    { source: "finance", target: "coo", weight: 1 },
  ],
};

// Integration logos for Integration Readiness page
export const INTEGRATIONS = [
  { name: "Salesforce", category: "CRM", logo: "SF", color: "#00A1E0" },
  { name: "SAP", category: "ERP", logo: "SAP", color: "#0FAAFF" },
  { name: "Oracle ERP", category: "ERP", logo: "ORC", color: "#F80000" },
  { name: "Microsoft 365", category: "Productivity", logo: "M365", color: "#0078D4" },
  { name: "Workday", category: "HR", logo: "WD", color: "#F36F21" },
  { name: "ServiceNow", category: "ERP", logo: "SN", color: "#81B5A1" },
  { name: "Slack", category: "Productivity", logo: "SLK", color: "#4A154B" },
  { name: "Tableau", category: "Analytics", logo: "TAB", color: "#E97627" },
  { name: "Power BI", category: "Analytics", logo: "PBI", color: "#F2C811" },
  { name: "Jira", category: "Productivity", logo: "JRA", color: "#0052CC" },
  { name: "HubSpot", category: "CRM", logo: "HS", color: "#FF7A59" },
  { name: "Snowflake", category: "Analytics", logo: "SNW", color: "#29B5E8" },
  { name: "NetSuite", category: "ERP", logo: "NS", color: "#2F9E44" },
  { name: "SAP SuccessFactors", category: "HR", logo: "SF2", color: "#0070F3" },
  { name: "ADP", category: "HR", logo: "ADP", color: "#D0021B" },
  { name: "Workday Finance", category: "Finance", logo: "WF", color: "#F36F21" },
  { name: "Oracle Finance", category: "Finance", logo: "OF", color: "#F80000" },
  { name: "Coupa", category: "Finance", logo: "CPA", color: "#E31837" },
  { name: "Looker", category: "Analytics", logo: "LKR", color: "#4285F4" },
  { name: "Google Workspace", category: "Productivity", logo: "GWS", color: "#4285F4" },
  { name: "Microsoft Dynamics", category: "ERP", logo: "MSF", color: "#0078D4" },
  { name: "Qlik", category: "Analytics", logo: "QLK", color: "#009845" },
  { name: "BambooHR", category: "HR", logo: "BHR", color: "#73C41D" },
  { name: "Concur", category: "Finance", logo: "CNR", color: "#0070F3" },
];

// Industries served
export const INDUSTRIES = [
  {
    id: "aerospace",
    name: "Aerospace & Defense",
    icon: "🛡️",
    description: "Mission-critical intelligence for defense contractors managing complex government relationships and supply chains.",
    metrics: { avgROI: "340%", timeToValue: "6 weeks", clients: "12+" },
    useCases: ["Contract pipeline visibility", "Compliance monitoring", "Talent intelligence", "Supplier risk"],
  },
  {
    id: "financial",
    name: "Financial Services",
    icon: "🏦",
    description: "Real-time regulatory and market intelligence for banks, asset managers, and insurance firms.",
    metrics: { avgROI: "280%", timeToValue: "4 weeks", clients: "18+" },
    useCases: ["Regulatory change tracking", "Risk aggregation", "M&A intelligence", "Performance benchmarking"],
  },
  {
    id: "healthcare",
    name: "Healthcare & Life Sciences",
    icon: "⚕️",
    description: "Operational and clinical intelligence for health systems and pharmaceutical companies.",
    metrics: { avgROI: "310%", timeToValue: "8 weeks", clients: "9+" },
    useCases: ["Clinical trial oversight", "Regulatory submissions", "Supply chain resilience", "Workforce planning"],
  },
  {
    id: "manufacturing",
    name: "Advanced Manufacturing",
    icon: "⚙️",
    description: "Production intelligence and supply chain visibility for global manufacturers.",
    metrics: { avgROI: "295%", timeToValue: "5 weeks", clients: "15+" },
    useCases: ["Production efficiency", "Quality signal detection", "Supplier intelligence", "Capacity planning"],
  },
  {
    id: "energy",
    name: "Energy & Utilities",
    icon: "⚡",
    description: "Grid, asset, and regulatory intelligence for energy companies navigating the transition.",
    metrics: { avgROI: "260%", timeToValue: "7 weeks", clients: "8+" },
    useCases: ["Asset performance", "Regulatory compliance", "ESG reporting", "Market intelligence"],
  },
  {
    id: "technology",
    name: "Enterprise Technology",
    icon: "💻",
    description: "Product, market, and talent intelligence for technology companies scaling globally.",
    metrics: { avgROI: "320%", timeToValue: "3 weeks", clients: "22+" },
    useCases: ["Product roadmap alignment", "Competitive intelligence", "Talent analytics", "Customer intelligence"],
  },
];

// Pricing tiers
export const PRICING_TIERS = [
  {
    id: "command",
    name: "Command",
    tagline: "For emerging enterprises",
    price: "Contact Sales",
    priceNote: "Starting at $48K/year",
    highlight: false,
    features: [
      "Up to 5 executive users",
      "Executive Dashboard",
      "Priority Intelligence Feed",
      "3 department integrations",
      "Standard onboarding",
      "Email support",
      "Quarterly business reviews",
    ],
    cta: "Request Access",
  },
  {
    id: "sovereign",
    name: "Sovereign",
    tagline: "For Fortune 1000 enterprises",
    price: "Contact Sales",
    priceNote: "Starting at $180K/year",
    highlight: true,
    features: [
      "Up to 25 executive users",
      "Full Executive Intelligence Suite",
      "Business DNA & Knowledge Graph",
      "Unlimited integrations",
      "Dedicated onboarding specialist",
      "24/7 priority support",
      "Monthly executive briefings",
      "Custom recommendation models",
      "API access",
    ],
    cta: "Request Access",
  },
  {
    id: "apex",
    name: "Apex",
    tagline: "For global enterprises",
    price: "Contact Sales",
    priceNote: "Custom enterprise pricing",
    highlight: false,
    features: [
      "Unlimited executive users",
      "Full platform + custom modules",
      "White-glove implementation",
      "Dedicated success team",
      "Custom AI model training",
      "On-premise deployment option",
      "SLA guarantees",
      "Board-level reporting",
      "Multi-entity support",
    ],
    cta: "Schedule Briefing",
  },
];
