export const PUBLIC_CONTACT = {
  email: "eagle@eagleeyeautomation.com",
  phoneDisplay: "+1 571-462-2407",
  mailto: "mailto:eagle@eagleeyeautomation.com",
  tel: "tel:+15714622407",
};

export const SETUP_FEE = {
  label: "One-Time Setup and Onboarding Fee",
  price: "$250",
  disclosure: "The one-time setup and onboarding fee is due when onboarding begins and is separate from the monthly subscription.",
  covers: [
    "Account setup",
    "Organization configuration",
    "GoHighLevel connection",
    "Location setup",
    "Initial data synchronization",
    "Dashboard configuration",
    "Basic customer training",
    "Launch support",
  ],
};

export const FOUNDING_CUSTOMER_PROMO_ENABLED = false;

export const FOUNDING_CUSTOMER_PLANS = [
  {
    id: "starter",
    name: "Starter",
    planCode: "FOUNDATION",
    price: "$99",
    cadence: "/month",
    customerType: "For a single-location business beginning with executive visibility.",
    locationLimit: "1 GoHighLevel location",
    cta: "Request Starter Demo",
    features: [
      "Owner Command Center access",
      "GoHighLevel connection",
      "Executive briefing from synchronized data",
      "Business health view when enough verified activity exists",
      "Integration status",
      "Secure owner sign-in",
    ],
  },
  {
    id: "growth",
    name: "Growth",
    planCode: "INTELLIGENCE",
    price: "$199",
    cadence: "/month",
    customerType: "For a growing business that needs clearer follow-up and operating visibility.",
    locationLimit: "Up to 3 GoHighLevel locations",
    cta: "Request Growth Demo",
    featured: true,
    features: [
      "Everything in Starter",
      "Multi-location command center views",
      "Executive timeline from verified events",
      "Knowledge graph when synchronized data is available",
      "AI recommendations when verified signals support them",
      "Launch support for leadership review",
    ],
  },
  {
    id: "scale",
    name: "Scale",
    planCode: "ENTERPRISE",
    price: "$299",
    cadence: "/month",
    customerType: "For a multi-location operator preparing for deeper executive intelligence.",
    locationLimit: "Up to 5 GoHighLevel locations",
    cta: "Request Scale Demo",
    features: [
      "Everything in Growth",
      "Expanded location setup",
      "Owner and operations review support",
      "Priority dashboard configuration",
      "Workflow automation planning",
      "GoHighLevel-first operating system roadmap",
    ],
  },
];

export const OPTIONAL_INTELLIGENCE_ADDONS = [
  {
    key: "ADDON_C2C_INTELLIGENCE",
    name: "C2C Intelligence Pack",
    price: "$99",
    cadence: "/month",
    billingType: "Monthly add-on",
    basePlanRequirement: "Requires an active EEOS base plan.",
    description: "Customer-to-customer referral and relationship intelligence.",
    whatItDoes: "Surfaces referral patterns, customer influence, and relationship opportunities from approved business signals.",
    whoItHelps: "Owners and operators who want more customer referrals without unmanaged outreach.",
    includedCapabilities: ["Referral signal review", "Relationship opportunity scoring", "Human-approved next actions"],
    exampleUseCase: "Identify satisfied customers who may introduce the business to similar high-fit prospects.",
    exclusions: "Does not guarantee referrals, leads, revenue, conversions, or execute outreach without approval.",
  },
  {
    key: "ADDON_C2B_INTELLIGENCE",
    name: "C2B Intelligence Pack",
    price: "$149",
    cadence: "/month",
    billingType: "Monthly add-on",
    basePlanRequirement: "Requires an active EEOS base plan.",
    description: "Customer-to-business intake and opportunity intelligence.",
    whatItDoes: "Analyzes inbound customer intent, intake quality, response timing, and conversion opportunities.",
    whoItHelps: "Teams that need to improve follow-up, appointment conversion, and intake discipline.",
    includedCapabilities: ["Intake signal analysis", "Follow-up gap detection", "Conversion opportunity scoring"],
    exampleUseCase: "Spot prospects who submitted forms or called but have not received a timely follow-up.",
    exclusions: "Does not replace staff judgment, guarantee conversion, or perform external execution without approval.",
  },
  {
    key: "ADDON_B2B_INTELLIGENCE",
    name: "B2B Intelligence Pack",
    price: "$149",
    cadence: "/month",
    billingType: "Monthly add-on",
    basePlanRequirement: "Requires an active EEOS base plan.",
    description: "Partner, referral-source, and business-to-business intelligence.",
    whatItDoes: "Evaluates referral-source performance, partner opportunities, and high-value business relationships.",
    whoItHelps: "Businesses that grow through partnerships, referral sources, and local business relationships.",
    includedCapabilities: ["Referral-source scoring", "Partner opportunity review", "B2B pipeline intelligence"],
    exampleUseCase: "Show which referral partner is creating the strongest revenue opportunity this month.",
    exclusions: "Does not guarantee referrals, revenue, partner response, or create external actions without approval.",
  },
  {
    key: "ADDON_GROWTH_INTELLIGENCE_SUITE",
    name: "Growth Intelligence Suite",
    price: "$299",
    cadence: "/month",
    billingType: "Monthly suite add-on",
    basePlanRequirement: "Requires an active EEOS base plan.",
    description: "Bundled C2C, C2B, and B2B intelligence for commercial organizations.",
    whatItDoes: "Combines customer, intake, and partner intelligence into one governed growth intelligence package.",
    whoItHelps: "Owners who want a complete growth intelligence layer across customer, prospect, and partner signals.",
    includedCapabilities: ["C2C Intelligence Pack", "C2B Intelligence Pack", "B2B Intelligence Pack", "Deduplicated entitlement resolution"],
    exampleUseCase: "Review the highest-value growth opportunities across referrals, inbound demand, and partner channels.",
    exclusions: "Does not include payment processing, guaranteed outcomes, or autonomous external execution.",
  },
  {
    key: "ADDON_ADDITIONAL_LOCATION",
    name: "Additional Location",
    price: "$49-$99",
    cadence: "per location/month",
    billingType: "Monthly location add-on",
    basePlanRequirement: "Requires an active EEOS base plan.",
    description: "Adds another approved operating location to the EEOS workspace.",
    whatItDoes: "Extends executive visibility, local health tracking, and location-level configuration to another office.",
    whoItHelps: "Multi-location businesses that need office-level visibility and company-wide rollups.",
    includedCapabilities: ["Location workspace", "Local reporting views", "Company rollup visibility"],
    exampleUseCase: "Add Charleston as a separate operating location while preserving company-wide leadership visibility.",
    exclusions: "Does not include third-party service fees, local staffing services, or guaranteed performance improvement.",
  },
  {
    key: "ADDON_ADDITIONAL_USER_PACK",
    name: "Additional User Pack",
    price: "Contact Sales",
    cadence: "",
    billingType: "Approved user-pack add-on",
    basePlanRequirement: "Requires an active EEOS base plan.",
    description: "Adds more approved users beyond the included plan access.",
    whatItDoes: "Expands secure access for additional executives, managers, employees, or approved collaborators.",
    whoItHelps: "Growing teams that need broader role-based EEOS access without changing the base plan.",
    includedCapabilities: ["Additional user seats", "Role-based access setup", "Permission review"],
    exampleUseCase: "Add a regional manager and operations lead to review location performance.",
    exclusions: "Does not include unrestricted access, cross-tenant visibility, or administrator rights by default.",
  },
  {
    key: "ADDON_ADDITIONAL_INDUSTRY_PACK",
    name: "Additional Industry Pack",
    price: "$49-$99",
    cadence: "/month per pack",
    billingType: "Monthly industry add-on",
    basePlanRequirement: "Requires an active EEOS base plan.",
    description: "Adds another industry configuration pack to shape terminology, KPIs, and executive context.",
    whatItDoes: "Personalizes EEOS language, operating assumptions, and dashboard context for another service category.",
    whoItHelps: "Companies serving multiple verticals that need different operating language and KPI emphasis.",
    includedCapabilities: ["Industry terminology", "KPI presets", "Executive context adjustments"],
    exampleUseCase: "Add an HVAC industry profile alongside home-care operations for a diversified operator.",
    exclusions: "Does not include custom software development, legal advice, or guaranteed market outcomes.",
  },
  {
    key: "ADDON_ADVANCED_CONNECTOR_PACK",
    name: "Advanced Connector Pack",
    price: "$99-$249",
    cadence: "/month",
    billingType: "Monthly connector add-on",
    basePlanRequirement: "Requires an active EEOS base plan.",
    description: "Supports approved advanced connector configuration after firewall and readiness review.",
    whatItDoes: "Prepares additional signal sources to pass through the Plugin Gateway, Firewall, Kernel, and Audit path.",
    whoItHelps: "Businesses that need more than the standard first-party operating connection.",
    includedCapabilities: ["Connector readiness review", "Signal mapping", "Firewall-governed intake planning"],
    exampleUseCase: "Prepare an accounting or reporting connector to send approved business signals into EEOS.",
    exclusions: "Does not activate live integrations, include third-party charges, or bypass Plugin Gateway approval.",
  },
  {
    key: "ADDON_CUSTOM_BRANDING",
    name: "Custom Branding",
    price: "$99",
    cadence: "/month plus setup",
    billingType: "Monthly branding add-on",
    basePlanRequirement: "Requires an active EEOS base plan.",
    description: "Applies approved customer brand presentation to supported EEOS workspace surfaces.",
    whatItDoes: "Adds logo, colors, and approved visual identity treatment where supported by the EEOS workspace.",
    whoItHelps: "Organizations that want their executive workspace to reflect their company identity.",
    includedCapabilities: ["Logo placement", "Brand color setup", "Workspace presentation review"],
    exampleUseCase: "Brand a customer command center for leadership and internal demos.",
    exclusions: "Does not include a public website redesign, trademark services, or unlimited design revisions.",
  },
  {
    key: "ADDON_API_ACCESS",
    name: "API Access",
    price: "$199-$499",
    cadence: "/month",
    billingType: "Monthly access add-on",
    basePlanRequirement: "Requires an active EEOS base plan.",
    description: "Provides approved API access planning for future controlled data exchange.",
    whatItDoes: "Defines governed API access through permissions, audit controls, tenant boundaries, and rate limits.",
    whoItHelps: "Technical teams that need structured access after security and integration readiness are complete.",
    includedCapabilities: ["Access review", "Permission scoping", "Audit and rate-limit planning"],
    exampleUseCase: "Prepare a customer-approved internal reporting connection without exposing private tenant data.",
    exclusions: "Does not include open access, live production secrets, unmanaged exports, or custom integration work.",
  },
  {
    key: "ADDON_PRIORITY_SUPPORT",
    name: "Priority Support",
    price: "$199-$499",
    cadence: "/month",
    billingType: "Monthly support add-on",
    basePlanRequirement: "Requires an active EEOS base plan.",
    description: "Adds enhanced support priority for approved EEOS operational needs.",
    whatItDoes: "Provides faster support routing, priority review windows, and structured issue follow-up.",
    whoItHelps: "Operators who need faster attention during onboarding, rollout, or critical business review periods.",
    includedCapabilities: ["Priority support queue", "Operational review cadence", "Escalation tracking"],
    exampleUseCase: "Escalate a launch-week configuration question for faster review.",
    exclusions: "Does not guarantee resolution time, include custom development, or replace third-party support.",
  },
  {
    key: "ADDON_DATA_RETENTION_EXTENSION",
    name: "Data Retention Extension",
    price: "Contact Sales",
    cadence: "",
    billingType: "Approved retention add-on",
    basePlanRequirement: "Requires an active EEOS base plan.",
    description: "Extends supported retention windows for approved EEOS records and intelligence history.",
    whatItDoes: "Defines longer retention for eligible audit, memory, decision, and operating history records.",
    whoItHelps: "Businesses with longer review, compliance, governance, or leadership history needs.",
    includedCapabilities: ["Retention review", "Eligible record scoping", "Governance documentation"],
    exampleUseCase: "Preserve longer executive decision history for annual leadership review.",
    exclusions: "Does not override legal obligations, store unsupported third-party source data, or reduce privacy controls.",
  },
  {
    key: "ADDON_ONBOARDING_TRAINING",
    name: "Onboarding and Training",
    price: "$1,500-$10,000",
    cadence: "one-time",
    billingType: "One-time services add-on",
    basePlanRequirement: "Requires an active EEOS base plan.",
    description: "Provides structured onboarding, configuration, and leadership training support.",
    whatItDoes: "Helps the customer configure EEOS, understand executive workflows, and prepare team adoption.",
    whoItHelps: "Companies that need guided launch support, leadership enablement, and operating rhythm design.",
    includedCapabilities: ["Workspace launch support", "Leadership training", "Configuration review"],
    exampleUseCase: "Run a guided onboarding program for a multi-location service business leadership team.",
    exclusions: "Does not include live integration activation, custom software development, or guaranteed business outcomes.",
  },
];

export const ADDON_DISPLAY_DISCLOSURES = [
  "Add-ons require an active EEOS base plan.",
  "Third-party service charges may be separate.",
  "Human approval remains required for governed actions.",
  "External execution is not included.",
  "Results, leads, referrals, revenue, or conversions are not guaranteed.",
];

export const EEOS_BRAIN_QUESTIONS = [
  "What can EEOS do for my business?",
  "How can EEOS help me grow?",
  "Which plan fits my company?",
  "How does EEOS connect to GoHighLevel?",
  "How can AI help me manage smarter?",
];
