do $$ begin
  create type eeos_user_role as enum ('user', 'admin');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type eeos_organization_type as enum ('platform_owner', 'customer');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type eeos_membership_plan as enum ('trial', 'starter', 'professional', 'enterprise');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type eeos_membership_status as enum ('active', 'suspended', 'cancelled', 'trial');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type eeos_membership_user_role as enum ('owner', 'executive', 'analyst', 'viewer');
exception when duplicate_object then null;
end $$;

create or replace function eeos_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists users (
  id bigint generated by default as identity primary key,
  open_id varchar(64) not null unique,
  name text,
  email varchar(320),
  login_method varchar(64),
  role eeos_user_role not null default 'user',
  password_hash text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

comment on column users.password_hash is
  'Nullable Stage A extension reserved for future first-party authentication; no login code reads it yet.';

comment on column users.is_active is
  'Approved PostgreSQL extension for immediate future account revocation; current MySQL reads remain authoritative.';

create unique index if not exists users_normalized_email_unique_idx
  on users (lower(email))
  where email is not null;

create table if not exists organizations (
  id bigint generated by default as identity primary key,
  slug varchar(64) not null unique,
  name varchar(256) not null,
  type eeos_organization_type not null,
  industry varchar(128),
  website varchar(512),
  logo_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_orgs_slug on organizations (slug);
create index if not exists idx_orgs_type on organizations (type);

create table if not exists memberships (
  id bigint generated by default as identity primary key,
  organization_id bigint not null,
  plan eeos_membership_plan not null default 'starter',
  status eeos_membership_status not null default 'active',
  ie_enabled boolean not null default true,
  ie_model_version varchar(32) default '1.0',
  max_subaccounts integer default 10,
  billing_email varchar(320),
  trial_ends_at timestamptz,
  renews_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_memberships_org on memberships (organization_id);
create index if not exists idx_memberships_status on memberships (status);

create table if not exists membership_users (
  id bigint generated by default as identity primary key,
  membership_id bigint not null,
  user_id bigint not null,
  role eeos_membership_user_role not null default 'viewer',
  is_active boolean not null default true,
  invited_at timestamptz not null default now(),
  accepted_at timestamptz
);

comment on table membership_users is
  'No composite uniqueness constraint is added in Stage A; production duplicates must be audited first.';

create index if not exists idx_membership_users_membership on membership_users (membership_id);
create index if not exists idx_membership_users_user on membership_users (user_id);

create table if not exists subaccounts (
  id bigint generated by default as identity primary key,
  membership_id bigint not null,
  ghl_location_id varchar(128) not null unique,
  ghl_company_id varchar(128),
  name varchar(256) not null,
  timezone varchar(64) default 'America/New_York',
  is_active boolean not null default true,
  ie_enabled boolean not null default true,
  connected_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_subaccounts_membership on subaccounts (membership_id);
create index if not exists idx_subaccounts_ghl_location on subaccounts (ghl_location_id);

do $$ begin
  alter table memberships
    add constraint memberships_organization_id_fk
    foreign key (organization_id) references organizations (id)
    on delete restrict not valid;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter table membership_users
    add constraint membership_users_membership_id_fk
    foreign key (membership_id) references memberships (id)
    on delete restrict not valid;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter table membership_users
    add constraint membership_users_user_id_fk
    foreign key (user_id) references users (id)
    on delete restrict not valid;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter table subaccounts
    add constraint subaccounts_membership_id_fk
    foreign key (membership_id) references memberships (id)
    on delete restrict not valid;
exception when duplicate_object then null;
end $$;

drop trigger if exists users_set_updated_at on users;
create trigger users_set_updated_at
before update on users
for each row execute function eeos_set_updated_at();

drop trigger if exists organizations_set_updated_at on organizations;
create trigger organizations_set_updated_at
before update on organizations
for each row execute function eeos_set_updated_at();

drop trigger if exists memberships_set_updated_at on memberships;
create trigger memberships_set_updated_at
before update on memberships
for each row execute function eeos_set_updated_at();

drop trigger if exists subaccounts_set_updated_at on subaccounts;
create trigger subaccounts_set_updated_at
before update on subaccounts
for each row execute function eeos_set_updated_at();
