do $$ begin
  create type eeos_billing_classification as enum ('INTERNAL_FOUNDER', 'INTERNAL_DEMO', 'COMMERCIAL');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type eeos_base_plan_code as enum ('FOUNDATION', 'INTELLIGENCE', 'ENTERPRISE');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type eeos_addon_key as enum (
    'ADDON_C2C_INTELLIGENCE',
    'ADDON_C2B_INTELLIGENCE',
    'ADDON_B2B_INTELLIGENCE',
    'ADDON_GROWTH_INTELLIGENCE_SUITE'
  );
exception when duplicate_object then null;
end $$;

do $$ begin
  create type eeos_addon_status as enum ('active', 'removed', 'expired');
exception when duplicate_object then null;
end $$;

create table if not exists commercial_organization_billing_profiles (
  organization_id bigint primary key references organizations(id) on delete restrict,
  billing_classification eeos_billing_classification not null,
  base_plan_code eeos_base_plan_code,
  base_plan_version integer not null default 2,
  base_plan_monthly_price integer not null default 0,
  billing_enabled boolean not null default false,
  payment_provider text,
  external_execution_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commercial_billing_no_unapproved_provider
    check (payment_provider is null),
  constraint commercial_billing_no_charge_without_provider
    check (billing_enabled = false),
  constraint commercial_billing_external_execution_blocked
    check (external_execution_enabled = false)
);

create table if not exists commercial_membership_addons (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete restrict,
  membership_id bigint not null references memberships(id) on delete restrict,
  addon_key eeos_addon_key not null,
  status eeos_addon_status not null default 'active',
  monthly_price integer not null,
  source text not null default 'platform_admin',
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  granted_by_user_id bigint references users(id) on delete set null,
  removed_by_user_id bigint references users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint commercial_addons_positive_price check (monthly_price >= 0),
  constraint commercial_addons_end_after_start check (ends_at is null or ends_at >= starts_at)
);

create unique index if not exists commercial_membership_addons_active_unique
  on commercial_membership_addons (membership_id, addon_key)
  where status = 'active';

create index if not exists commercial_addons_org_status_idx
  on commercial_membership_addons (organization_id, status, starts_at desc);

create table if not exists commercial_addon_audit_events (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references organizations(id) on delete restrict,
  membership_id bigint references memberships(id) on delete set null,
  actor_user_id bigint references users(id) on delete set null,
  action text not null,
  addon_key eeos_addon_key,
  previous_value jsonb not null default '{}'::jsonb,
  next_value jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists commercial_addon_audit_org_time_idx
  on commercial_addon_audit_events (organization_id, created_at desc);
