import { useEffect,useMemo,useState,type ReactNode } from "react";
import { ArrowLeft,ArrowRight,Brain,CircleCheck,Expand,ExternalLink,Pause,Play,RefreshCcw,RotateCcw,ShieldCheck,Sparkles,X } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const gold="#C9A227";
const health=[
  {name:"Virginia",status:"Healthy benchmark",score:94,revenue:"+8%",coverage:"96%",conversion:"72%",assessment:"91%",satisfaction:"94%",compliance:"100%",tone:"emerald"},
  {name:"South Carolina",status:"Operational risk",score:68,revenue:"−4%",coverage:"71%",conversion:"48%",assessment:"76%",satisfaction:"84%",compliance:"96%",tone:"rose"},
  {name:"Florida",status:"Growth opportunity",score:82,revenue:"+14%",coverage:"88%",conversion:"51%",assessment:"54%",satisfaction:"90%",compliance:"98%",tone:"amber"},
];
const timeline=["New staffing-risk signal","Conversion decline connected","Recommendation generated","Executive review","Workflow prepared","Goal created","Outcome measurement scheduled"];
const opportunities=[
  {domain:"C2C",title:"Family referral signal",detail:"Community caregiver network · human review pending",confidence:"86%",source:"Synthetic community signal"},
  {domain:"C2B",title:"Prospective client opportunity",detail:"Florida location fit · human approval required",confidence:"82%",source:"Synthetic inquiry pattern"},
  {domain:"B2B",title:"Hospital transition partnership",detail:"Referral potential · no outreach performed",confidence:"79%",source:"Synthetic partner evidence"},
];
const loop=["Collect","Analyze","Recommend","Human Decision","Outcome","Measure","Calibrate","Improve"];

export default function DemoPresentation(){
  const definition=trpc.demo.presenterNotes.useQuery(undefined,{retry:false});
  const state=trpc.demo.presentationState.useQuery(undefined,{retry:false});
  const [step,setStep]=useState(0);const [notes,setNotes]=useState(false);const [mode,setMode]=useState<"guided"|"self-guided">("guided");const [playing,setPlaying]=useState(true);const [industry,setIndustry]=useState("Home Care");
  const start=trpc.demo.startPresentation.useMutation({onSuccess:r=>{setStep(r.currentStep);state.refetch()},onError:e=>toast.error(e.message)});
  const advance=trpc.demo.advancePresentation.useMutation({onSuccess:r=>{setStep(r.currentStep);state.refetch()},onError:e=>toast.error(e.message)});
  const previous=trpc.demo.previousPresentation.useMutation({onSuccess:r=>{setStep(r.currentStep);state.refetch()},onError:e=>toast.error(e.message)});
  const complete=trpc.demo.completePresentation.useMutation({onSuccess:()=>state.refetch(),onError:e=>toast.error(e.message)});
  const restart=trpc.demo.restartPresentation.useMutation({onSuccess:r=>{setStep(r.currentStep);state.refetch()},onError:e=>toast.error(e.message)});
  const reset=trpc.demo.reset.useMutation({onSuccess:async()=>{toast.success("Synthetic baseline restored");setStep(0);await state.refetch()},onError:e=>toast.error(e.message)});
  useEffect(()=>{if(state.data){setStep(Math.max(0,Math.min(13,state.data.currentStep)));setMode(state.data.mode)}},[state.data]);
  const steps=definition.data?.steps??[];const current=steps[step];
  const goNext=()=>{if(step===13){complete.mutate();return}advance.mutate({currentStep:step})};
  const goPrevious=()=>previous.mutate({currentStep:step});
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement)return;if(event.key==="ArrowRight")goNext();if(event.key==="ArrowLeft")goPrevious();if(event.key==="Escape")window.location.href="/admin/demo-center";if(event.key.toLowerCase()==="f")document.documentElement.requestFullscreen?.();if(event.key.toLowerCase()==="r"&&confirm("Restart the guided presentation at step one?"))restart.mutate({confirmed:true});};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)});
  if(definition.isLoading)return <div className="grid min-h-screen place-items-center bg-[#080808] text-white">Preparing the flagship experience…</div>;
  if(definition.error)return <div className="grid min-h-screen place-items-center bg-[#080808] p-8 text-center text-white"><div><ShieldCheck className="mx-auto mb-4 text-[#C9A227]"/><h1 className="text-2xl font-semibold">Authorized presenter access required</h1><p className="mt-2 text-white/50">{definition.error.message}</p></div></div>;
  return <div className="min-h-screen bg-[#080808] text-white selection:bg-[#C9A227]/30">
    <header className="fixed inset-x-0 top-0 z-40 border-b border-white/10 bg-black/85 px-4 py-3 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl border border-[#C9A227]/40 bg-[#C9A227]/10"><Brain className="h-5 w-5 text-[#C9A227]"/></div><div className="min-w-0"><p className="truncate text-xs font-bold tracking-[.2em] text-[#C9A227]">EEOS FLAGSHIP DEMO</p><p className="truncate text-xs text-white/45">Summit Home Services Group · Synthetic</p></div></div><div className="hidden items-center gap-2 md:flex"><button onClick={()=>{const next=mode==="guided"?"self-guided":"guided";setMode(next);start.mutate({mode:next})}} className="rounded-full border border-white/15 px-3 py-1.5 text-xs">{mode==="guided"?"Guided Mode":"Self-Guided Mode"}</button><button onClick={()=>setNotes(!notes)} className="rounded-full border border-white/15 px-3 py-1.5 text-xs">{notes?"Hide":"Show"} notes</button><button aria-label="Fullscreen" onClick={()=>document.documentElement.requestFullscreen?.()} className="rounded-full border border-white/15 p-2"><Expand className="h-4 w-4"/></button><a href="/admin/demo-center" aria-label="Exit presentation" className="rounded-full border border-white/15 p-2"><X className="h-4 w-4"/></a></div></div></header>
    <main className="mx-auto flex min-h-screen max-w-7xl items-center px-4 pb-28 pt-24"><div className="w-full"><div className="mb-5 flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#C9A227]">Step {step+1} of 14 · {current?.eyebrow}</p><h1 className="mt-2 text-3xl font-bold md:text-5xl">{current?.title}</h1></div><span className="hidden rounded-full border border-[#C9A227]/30 bg-[#C9A227]/10 px-3 py-1 text-xs text-[#C9A227] sm:block">Synthetic Demo</span></div><StepBody step={step} playing={playing} setPlaying={setPlaying} setStep={setStep} industry={industry} setIndustry={setIndustry}/>{notes&&current?.presenterNote&&<PresenterNote note={current.presenterNote}/>}</div></main>
    <footer className="fixed inset-x-0 bottom-0 z-40 border-t border-white/10 bg-black/90 px-4 py-3 backdrop-blur-xl"><div className="mx-auto max-w-7xl"><div className="mb-3 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-[#C9A227] transition-all" style={{width:`${((step+1)/14)*100}%`}}/></div><div className="flex items-center justify-between gap-3"><div className="flex gap-2"><button disabled={step===0||previous.isPending} onClick={goPrevious} className="control"><ArrowLeft className="h-4 w-4"/><span className="hidden sm:inline">Previous</span></button><button onClick={()=>{if(confirm("Restart the guided presentation at step one?"))restart.mutate({confirmed:true})}} className="control"><RotateCcw className="h-4 w-4"/><span className="hidden sm:inline">Restart</span></button><button onClick={()=>{if(confirm("Restore the certified synthetic scenario baseline?"))reset.mutate()}} className="control hidden md:flex"><RefreshCcw className="h-4 w-4"/>Reset scenario</button></div><p className="hidden text-xs text-white/45 lg:block">{current?.title} · {current?.durationMinutes} min</p><button disabled={advance.isPending} onClick={goNext} className="inline-flex items-center gap-2 rounded-xl bg-[#C9A227] px-5 py-2.5 text-sm font-semibold text-black">{step===13?"Complete":"Next"}<ArrowRight className="h-4 w-4"/></button></div></div></footer>
  </div>
}

function StepBody({step,playing,setPlaying,setStep,industry,setIndustry}:{step:number;playing:boolean;setPlaying:(v:boolean)=>void;setStep:(v:number)=>void;industry:string;setIndustry:(v:string)=>void}){
  const approve=trpc.demo.approvePresentationWorkflow.useMutation({onSuccess:r=>toast.success(`Workflow ${r.status}; external execution remains blocked`),onError:e=>toast.error(e.message)});
  if(step===0)return <Panel className="relative min-h-[520px] overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_40%,rgba(201,162,39,.25),transparent_45%)]"/><div className="relative grid min-h-[480px] place-items-center text-center"><div><Sparkles className="mx-auto h-12 w-12 text-[#C9A227]"/><p className="mt-8 text-sm uppercase tracking-[.35em] text-[#C9A227]">EEOS</p><h2 className="mt-4 text-4xl font-bold md:text-7xl">Fortune 500 Intelligence.</h2><p className="mt-4 text-xl text-white/55">Built for Every Business.</p><p className="mt-10 text-sm text-white/35">Approved cinematic placeholder · Live platform continues without media</p><div className="mt-7 flex flex-wrap justify-center gap-3"><button onClick={()=>setPlaying(!playing)} className="primary">{playing?<Pause/>:<Play/>}{playing?"Pause":"Play"}</button><button onClick={()=>setPlaying(true)} className="secondary"><RotateCcw/>Restart</button><button onClick={()=>setStep(1)} className="secondary">Skip intro</button><button onClick={()=>setStep(1)} className="primary">Continue to live demo<ArrowRight/></button></div></div></div></Panel>;
  if(step===1)return <Panel><div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><Label>Summit Home Services Group</Label><h2 className="mt-5 text-4xl font-bold md:text-6xl">Monday Executive Briefing</h2><p className="mt-6 max-w-3xl text-xl leading-relaxed text-white/65">“South Carolina requires immediate staffing attention, while Florida presents a near-term growth opportunity.”</p><div className="mt-8 flex flex-wrap gap-2"><Tag>Overall status: Focused attention</Tag><Tag>3 active locations</Tag><Tag>{new Date().toLocaleDateString()}</Tag></div></div><BrainOrb/></div></Panel>;
  if(step===2)return <Panel><div className="grid gap-4 lg:grid-cols-3">{health.map(x=><article key={x.name} className="rounded-2xl border border-white/10 bg-black/25 p-5"><div className="flex items-start justify-between"><div><p className="text-xl font-semibold">{x.name}</p><p className="mt-1 text-xs text-[#C9A227]">{x.status}</p></div><p className="text-3xl font-bold">{x.score}</p></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Metric label="Revenue" value={x.revenue}/><Metric label="Staffing" value={x.coverage}/><Metric label="Inquiry conversion" value={x.conversion}/><Metric label="Assessment" value={x.assessment}/><Metric label="Satisfaction" value={x.satisfaction}/><Metric label="Compliance" value={x.compliance}/></div></article>)}</div><p className="mt-5 text-sm text-white/45">Overall health score: <b className="text-white">81</b> · Synthetic scenario snapshot</p></Panel>;
  if(step===3)return <Panel><div className="grid gap-4 md:grid-cols-5">{[["FACT","Coverage 71% · 19 open shifts"],["DERIVED METRIC","Coverage gap materially exceeds Virginia benchmark"],["INFERENCE","Capacity risk may constrain service quality and growth"],["RECOMMENDATION","Stabilize coverage before higher-acuity intake"],["EXECUTIVE DECISION","Human approval required"]].map(([a,b],i)=><div key={a} className="rounded-2xl border border-white/10 bg-black/25 p-5"><p className="text-xs font-bold text-[#C9A227]">{i+1}. {a}</p><p className="mt-4 text-sm leading-relaxed text-white/65">{b}</p></div>)}</div><div className="mt-5 grid gap-3 md:grid-cols-4"><Metric label="Confidence" value="92%"/><Metric label="Strategic priority" value="Immediate"/><Metric label="Freshness" value="Scenario current"/><Metric label="Assumption" value="Demand remains stable"/></div></Panel>;
  if(step===4)return <Panel><Label>Primary recommendation</Label><h2 className="mt-4 max-w-5xl text-3xl font-bold md:text-5xl">Reduce the South Carolina caregiver coverage gap before accepting additional high-acuity cases.</h2><div className="mt-8 grid gap-4 md:grid-cols-4"><Info title="Why it matters">Protect service capacity and customer experience.</Info><Info title="Expected impact">Lower uncovered shifts and overtime; outcome not guaranteed.</Info><Info title="Recommended action">Prepare a seven-day recruitment and scheduling plan.</Info><Info title="No-action risk">Capacity pressure may intensify and constrain safe growth.</Info></div></Panel>;
  if(step===5)return <CopilotDemo/>;
  if(step===6)return <Panel><div className="grid gap-3 md:grid-cols-7">{timeline.map((x,i)=><div key={x} className="relative rounded-2xl border border-white/10 bg-black/25 p-4"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#C9A227] text-xs font-bold text-black">{i+1}</span><p className="mt-4 text-sm font-medium">{x}</p>{i<6&&<ArrowRight className="absolute -right-3 top-7 z-10 hidden h-5 w-5 text-[#C9A227] md:block"/>}</div>)}</div></Panel>;
  if(step===7)return <Panel><div className="grid gap-4 md:grid-cols-3">{opportunities.map(x=><Info key={x.domain} title={`${x.domain} · ${x.title}`}><p>{x.detail}</p><p className="mt-3 text-[#C9A227]">Confidence {x.confidence}</p><p className="mt-1 text-xs text-white/35">Source: {x.source}</p></Info>)}</div><p className="mt-5 text-sm text-white/45">Synthetic opportunities · human review required · no outreach or external CRM write</p></Panel>;
  if(step===8)return <Panel><div className="grid gap-8 lg:grid-cols-[1fr_1.2fr]"><div><Label>Active primary pack</Label><h2 className="mt-4 text-5xl font-bold">Home Care</h2><p className="mt-4 text-white/55">One Brain. One platform. Configured for each industry.</p></div><div><p className="mb-3 text-xs uppercase tracking-widest text-white/40">Presentation-only preview</p><div className="flex flex-wrap gap-2">{["Home Care","Healthcare","Church","HVAC","Construction","Professional Services"].map(x=><button key={x} onClick={()=>setIndustry(x)} className={`rounded-full border px-4 py-2 text-sm ${industry===x?"border-[#C9A227] bg-[#C9A227]/15 text-[#C9A227]":"border-white/15"}`}>{x}</button>)}</div><Info title={`${industry} preview`}><p>{industry==="Home Care"?"Caregiver coverage · assessment completion · client satisfaction":"Terminology and KPI preview only. Saved organization configuration remains Home Care."}</p></Info></div></div></Panel>;
  if(step===9)return <Panel><div className="grid gap-4 lg:grid-cols-3"><Info title="Evidence & confidence">Four synthetic signals · 92% bounded confidence</Info><Info title="Risk gates & policy">Protected action · human executive approval required</Info><Info title="External execution"><span className="text-emerald-400">Blocked</span> · no email, SMS, CRM, finance, or connector write</Info></div><div className="mt-6 rounded-2xl border border-[#C9A227]/30 bg-[#C9A227]/5 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-semibold">Seven-day caregiver recruitment and scheduling stabilization plan</p><p className="mt-1 text-sm text-white/45">Prepared workflow · audit attribution enabled</p></div><div className="flex flex-wrap gap-2"><button disabled={approve.isPending} onClick={()=>{if(confirm("Approve this synthetic workflow? External execution will remain blocked."))approve.mutate()}} className="primary"><CircleCheck/>{approve.isPending?"Approving…":"Approve governed workflow"}</button><a href="/executive-automation" className="secondary">Open live module<ExternalLink/></a></div></div></div></Panel>;
  if(step===10)return <Panel><h2 className="text-3xl font-bold">Reduce South Carolina uncovered shifts within seven days.</h2><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric label="Baseline" value="19 shifts"/><Metric label="Target" value="≤ 8 shifts"/><Metric label="Owner" value="SC Operations"/><Metric label="Due" value="7 days"/><Metric label="Progress" value="Baseline"/><Metric label="Source" value="Verified scheduling"/></div><p className="mt-5 text-sm text-white/45">Related recommendation and governed workflow remain linked for outcome attribution.</p></Panel>;
  if(step===11)return <Panel><div className="grid gap-3 sm:grid-cols-4 lg:grid-cols-8">{loop.map((x,i)=><div key={x} className="relative rounded-2xl border border-white/10 bg-black/25 p-4 text-center"><CircleCheck className="mx-auto h-5 w-5 text-[#C9A227]"/><p className="mt-3 text-sm font-medium">{x}</p>{i<7&&<ArrowRight className="absolute -right-3 top-1/2 hidden h-5 w-5 text-[#C9A227] lg:block"/>}</div>)}</div><div className="mt-6 grid gap-3 md:grid-cols-4"><Info title="Evidence threshold">No learning from unverified outcomes.</Info><Info title="Bounded calibration">Confidence adjustments remain constrained.</Info><Info title="Tenant isolation">Organization memory never crosses boundaries.</Info><Info title="Measured improvement">Verified outcomes make recommendations more useful.</Info></div></Panel>;
  if(step===12)return <Panel><div className="grid gap-4 md:grid-cols-3"><Metric label="Demo organization" value="Healthy"/><Metric label="Platform health" value="Green"/><Metric label="Connector health" value="Operational"/><Metric label="Recommendation quality" value="Evidence governed"/><Metric label="Adoption" value="Anonymous aggregate"/><Metric label="Audit evidence" value="Attributable"/></div><p className="mt-6 rounded-xl border border-white/10 p-4 text-sm text-white/50">Platform Owner governance uses privacy-safe aggregates. Tenant-confidential operational data is not displayed outside authorized context.</p></Panel>;
  return <Panel className="text-center"><p className="text-sm uppercase tracking-[.35em] text-[#C9A227]">EEOS</p><h2 className="mt-5 text-4xl font-bold md:text-7xl">Fortune 500 Intelligence.</h2><p className="mt-4 text-2xl text-white/55">Built for Every Business.</p><p className="mt-10 text-xl">Stop Managing. Start Leading.</p><div className="mt-10 flex flex-wrap justify-center gap-3"><button onClick={()=>setStep(0)} className="secondary"><RotateCcw/>Restart demo</button><a href="/admin/demo-center" className="secondary">Return to Demo Center</a><a href="/executive-home" className="primary">Enter live platform<ArrowRight/></a></div></Panel>;
}

function CopilotDemo(){const [question,setQuestion]=useState("What should I focus on today?");const query=trpc.demo.presentationCopilot.useQuery({question},{retry:false});const samples=useMemo(()=>["What should I focus on today?","Why is South Carolina the highest priority?","What should we learn from Virginia?","What is the Florida growth opportunity?","What happens if we do nothing?","Tell me next year's exact revenue"],[]);return <Panel><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div><Label>Guided questions</Label><div className="mt-4 grid gap-2">{samples.map(x=><button key={x} onClick={()=>setQuestion(x)} className={`rounded-xl border p-3 text-left text-sm ${question===x?"border-[#C9A227] bg-[#C9A227]/10":"border-white/10"}`}>{x}</button>)}</div></div><div className="rounded-2xl border border-white/10 bg-black/25 p-6"><div className="flex items-center gap-3"><Brain className="text-[#C9A227]"/><p className="font-semibold">Executive Copilot</p></div><p className="mt-5 text-lg leading-relaxed text-white/75">{query.data?.answer??"Reviewing authorized synthetic evidence…"}</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><Metric label="Confidence" value={`${query.data?.confidence??0}%`}/><Metric label="Classification" value={query.data?.classification?.replace("_"," ")??"—"}/></div><p className="mt-4 text-xs text-white/40">Evidence: {query.data?.evidence.join(" · ")||"Insufficient authorized evidence"}</p><p className="mt-2 text-xs text-white/40">Source context: {query.data?.source??"—"}</p></div></div></Panel>}
function Panel({children,className=""}:{children:ReactNode;className?:string}){return <section className={`rounded-3xl border border-white/10 bg-[#121212] p-5 shadow-2xl md:p-8 ${className}`}>{children}</section>}
function PresenterNote({note}:{note:{say:string;click:string;notice:string;expected:string;fallback:string;maxTime:string}}){return <aside className="mt-4 rounded-2xl border border-[#C9A227]/30 bg-[#C9A227]/5 p-5"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-widest text-[#C9A227]">Presenter notes</p><p className="text-xs text-white/40">Maximum {note.maxTime}</p></div><div className="mt-4 grid gap-3 md:grid-cols-3"><Info title="What to say">{note.say}</Info><Info title="What to click">{note.click}</Info><Info title="Audience should notice">{note.notice}</Info><Info title="Expected response">{note.expected}</Info><Info title="Safe fallback">{note.fallback}</Info></div></aside>}
function BrainOrb(){return <div className="grid min-h-64 place-items-center"><div className="relative grid h-52 w-52 place-items-center rounded-full border border-[#C9A227]/40 bg-[radial-gradient(circle,rgba(201,162,39,.25),rgba(201,162,39,.03)_60%,transparent_61%)]"><div className="absolute inset-4 animate-pulse rounded-full border border-[#C9A227]/20"/><Brain className="h-16 w-16 text-[#C9A227]"/></div></div>}
function Label({children}:{children:ReactNode}){return <span className="rounded-full border border-[#C9A227]/30 bg-[#C9A227]/10 px-3 py-1 text-xs font-semibold uppercase tracking-widest text-[#C9A227]">{children}</span>}
function Tag({children}:{children:ReactNode}){return <span className="rounded-full border border-white/15 px-3 py-1.5 text-xs text-white/60">{children}</span>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/10 bg-black/25 p-3"><p className="text-lg font-semibold capitalize">{value}</p><p className="mt-1 text-[11px] text-white/40">{label}</p></div>}
function Info({title,children}:{title:string;children:ReactNode}){return <div className="mt-4 rounded-2xl border border-white/10 bg-black/25 p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#C9A227]">{title}</p><div className="mt-3 text-sm leading-relaxed text-white/60">{children}</div></div>}
