import { useState } from "react";
import { CheckCircle2, ClipboardCheck, ShieldCheck, Target, XCircle } from "lucide-react";
import { toast } from "sonner";
import Footer from "@/components/Footer";
import Navigation from "@/components/Navigation";
import OrganizationWelcomeBanner from "@/components/OrganizationWelcomeBanner";
import { trpc } from "@/lib/trpc";

export default function ExecutiveAutomation() {
  const dashboard = trpc.automation.dashboard.useQuery(undefined, { retry: false, refetchInterval: 30000 });
  const [templateKey, setTemplateKey] = useState("create-task");
  const [title, setTitle] = useState("");
  const [evidence, setEvidence] = useState("");
  const prepare = trpc.automation.prepare.useMutation({ onSuccess: async () => { toast.success("Workflow prepared"); setTitle(""); setEvidence(""); await dashboard.refetch(); }, onError: (error) => toast.error(error.message) });
  const decide = trpc.automation.decide.useMutation({ onSuccess: async (_, variables) => { toast.success(`Workflow ${variables.decision}`); await dashboard.refetch(); }, onError: (error) => toast.error(error.message) });
  const templates = dashboard.data?.templates ?? [];

  return <div className="min-h-screen bg-[#0B0B0B] text-white"><Navigation /><main className="mx-auto max-w-7xl px-4 pb-16 pt-24 sm:px-6 lg:px-8">
    <OrganizationWelcomeBanner />
    <section className="rounded-3xl border border-white/10 bg-[#141414] p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#C9A227]">Executive Automation</p><h1 className="mt-3 text-4xl font-bold">Decision Orchestration</h1><p className="mt-3 max-w-3xl text-sm text-white/55">The Brain prepares governed business work. Protected actions stay blocked until an executive decides, and Phase 5 never performs autonomous external writes.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Awaiting approval" value={(dashboard.data?.workflows ?? []).filter((item) => item.status === "awaiting_approval").length} /><Metric label="Prepared workflows" value={dashboard.data?.workflows.length ?? 0} /><Metric label="Active goals" value={(dashboard.data?.goals ?? []).filter((item) => item.status === "active").length} /></div></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]">
      <form className="rounded-3xl border border-white/10 bg-[#141414] p-6" onSubmit={(event) => { event.preventDefault(); prepare.mutate({ templateKey, title, payload: { title }, evidence: [evidence], confidence: 80, riskScore: 20 }); }}><div className="flex items-center gap-3"><ClipboardCheck className="h-5 w-5 text-[#C9A227]"/><h2 className="text-xl font-semibold">Prepare workflow</h2></div><label className="mt-5 block text-xs uppercase tracking-wide text-white/45">Template</label><select className="mt-2 w-full rounded-xl border border-white/15 bg-black/30 p-3" value={templateKey} onChange={(event) => setTemplateKey(event.target.value)}>{templates.map((item) => <option key={item.templateKey} value={item.templateKey}>{item.name}</option>)}</select><label className="mt-4 block text-xs uppercase tracking-wide text-white/45">Action title</label><input required className="mt-2 w-full rounded-xl border border-white/15 bg-black/30 p-3" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="What should be prepared?" /><label className="mt-4 block text-xs uppercase tracking-wide text-white/45">Verified evidence</label><textarea required className="mt-2 min-h-24 w-full rounded-xl border border-white/15 bg-black/30 p-3" value={evidence} onChange={(event) => setEvidence(event.target.value)} placeholder="Evidence supporting this action" /><button disabled={prepare.isPending} className="mt-5 rounded-xl bg-[#C9A227] px-5 py-3 font-semibold text-black disabled:opacity-50">{prepare.isPending ? "Preparing…" : "Prepare for review"}</button></form>
      <section className="rounded-3xl border border-white/10 bg-[#141414] p-6"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-[#C9A227]"/><h2 className="text-xl font-semibold">Approval queue</h2></div><div className="mt-5 space-y-3">{dashboard.isLoading ? <p className="text-sm text-white/45">Loading governed work…</p> : (dashboard.data?.workflows ?? []).length ? dashboard.data!.workflows.map((item) => <article key={item.id} className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{item.title}</h3><p className="mt-1 text-xs text-white/45">{item.actionType.replaceAll("_", " ")} · {item.confidence}% confidence · risk {item.riskScore}</p></div><span className="rounded-full border border-white/15 px-3 py-1 text-xs capitalize">{item.status.replaceAll("_", " ")}</span></div>{item.status === "awaiting_approval" && <div className="mt-4 flex gap-2"><button onClick={() => decide.mutate({ workflowId: item.id, decision: "approved" })} className="inline-flex items-center gap-2 rounded-lg bg-emerald-500/15 px-3 py-2 text-sm text-emerald-300"><CheckCircle2 className="h-4 w-4"/>Approve</button><button onClick={() => decide.mutate({ workflowId: item.id, decision: "rejected" })} className="inline-flex items-center gap-2 rounded-lg bg-red-500/15 px-3 py-2 text-sm text-red-300"><XCircle className="h-4 w-4"/>Reject</button></div>}</article>) : <p className="rounded-xl border border-dashed border-white/15 p-8 text-center text-sm text-white/45">No workflows have been prepared.</p>}</div></section>
    </section>
    <section className="mt-6 rounded-3xl border border-white/10 bg-[#141414] p-6"><div className="flex items-center gap-3"><Target className="h-5 w-5 text-[#C9A227]"/><h2 className="text-xl font-semibold">Business goals</h2></div><div className="mt-4 grid gap-3 md:grid-cols-3">{(dashboard.data?.goals ?? []).map((goal) => <article key={goal.id} className="rounded-xl border border-white/10 p-4"><p className="text-xs uppercase text-[#C9A227]">{goal.goalType.replaceAll("_", " ")}</p><h3 className="mt-2 font-semibold">{goal.title}</h3><p className="mt-2 text-sm text-white/50">{goal.currentValue ?? "—"} / {goal.target} {goal.unit}</p></article>)}</div></section>
  </main><Footer hideConnectionLinks /></div>;
}

function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-white/45">{label}</p></div>; }
