import { useEffect, useState } from "react";
import { BarChart3, Building2, CheckCircle2, Network, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import Footer from "@/components/Footer";
import Navigation from "@/components/Navigation";
import OrganizationWelcomeBanner from "@/components/OrganizationWelcomeBanner";
import { trpc } from "@/lib/trpc";

export default function IndustryIntelligence() {
  const catalog = trpc.industry.catalog.useQuery(undefined,{retry:false});
  const context = trpc.industry.context.useQuery(undefined,{retry:false,refetchInterval:60000});
  const [selected,setSelected]=useState<string[]>([]); const [primary,setPrimary]=useState("");
  useEffect(()=>{ if(context.data?.selected.length&&!selected.length){const keys=context.data.selected.map((item)=>item.packKey);setSelected(keys);setPrimary(context.data.selected.find((item)=>item.isPrimary)?.packKey??keys[0]);}},[context.data,selected.length]);
  const configure=trpc.industry.configure.useMutation({onSuccess:async()=>{toast.success("Industry Packs configured");await context.refetch();},onError:(error)=>toast.error(error.message)});
  const active=context.data?.context;
  const toggle=(key:string)=>setSelected((current)=>current.includes(key)?current.filter((item)=>item!==key):[...current,key]);
  return <div className="min-h-screen bg-[#0B0B0B] text-white"><Navigation/><main className="mx-auto max-w-7xl px-4 pb-16 pt-24 sm:px-6 lg:px-8"><OrganizationWelcomeBanner/>
    <section className="rounded-3xl border border-white/10 bg-[#141414] p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#C9A227]">Industry Intelligence Platform</p><h1 className="mt-3 text-4xl font-bold">Configure the Brain for your industry</h1><p className="mt-3 max-w-3xl text-sm text-white/55">Select one or more intelligence packs. EEOS remains one platform while terminology, KPIs, rules, opportunities, and C2C/C2B/B2B intelligence adapt to your organization.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Selected packs" value={active?.packs.length??0}/><Metric label="Configured KPIs" value={active?.kpis.length??0}/><Metric label="Business rules" value={active?.businessRules.length??0}/></div></section>
    <section className="mt-6 rounded-3xl border border-white/10 bg-[#141414] p-6"><div className="flex items-center gap-3"><Building2 className="h-5 w-5 text-[#C9A227]"/><h2 className="text-xl font-semibold">Industry Packs</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(catalog.data??[]).map((pack)=><button key={pack.key} onClick={()=>toggle(pack.key)} className={`rounded-xl border p-4 text-left ${selected.includes(pack.key)?"border-[#C9A227] bg-[#C9A227]/10":"border-white/10"}`}><div className="flex items-center justify-between"><span className="font-semibold">{pack.name}</span>{selected.includes(pack.key)&&<CheckCircle2 className="h-4 w-4 text-[#C9A227]"/>}</div><p className="mt-2 text-xs text-white/45">{pack.kpis.slice(0,3).join(" · ")}</p>{selected.includes(pack.key)&&<label className="mt-3 flex items-center gap-2 text-xs" onClick={(event)=>event.stopPropagation()}><input type="radio" name="primary-pack" checked={primary===pack.key} onChange={()=>setPrimary(pack.key)}/>Primary terminology</label>}</button>)}</div><button disabled={!selected.length||!primary||configure.isPending} onClick={()=>configure.mutate({packKeys:selected as any,primaryPackKey:primary as any})} className="mt-5 rounded-xl bg-[#C9A227] px-5 py-3 font-semibold text-black disabled:opacity-40">{configure.isPending?"Configuring…":"Apply Industry Packs"}</button></section>
    {active?.packs.length?<><section className="mt-6 grid gap-6 lg:grid-cols-2"><Panel icon={BarChart3} title="Executive KPIs" items={active.kpis}/><Panel icon={ShieldCheck} title="Compliance and business rules" items={[...active.complianceRules,...active.businessRules]}/><Panel icon={Network} title="Opportunity types" items={active.opportunityTypes}/><Panel icon={Building2} title="Dashboard sections" items={active.dashboardSections}/></section><section className="mt-6 grid gap-4 md:grid-cols-3"><Panel icon={Network} title="C2C Intelligence" items={active.intelligence.c2c}/><Panel icon={Network} title="C2B Intelligence" items={active.intelligence.c2b}/><Panel icon={Network} title="B2B Intelligence" items={active.intelligence.b2b}/></section></>:null}
  </main><Footer hideConnectionLinks/></div>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-white/45">{label}</p></div>}
function Panel({icon:Icon,title,items}:{icon:typeof Network;title:string;items:string[]}){return <section className="rounded-2xl border border-white/10 bg-[#141414] p-5"><div className="flex items-center gap-3"><Icon className="h-5 w-5 text-[#C9A227]"/><h2 className="font-semibold">{title}</h2></div><ul className="mt-4 space-y-2 text-sm text-white/60">{items.map((item)=><li key={item} className="rounded-lg border border-white/5 px-3 py-2">{item}</li>)}</ul></section>}
